// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRNJCnsDT5vOWHJRf-KVv1RVV-D6P9jQ',
    appId: '1:688190827051:web:85a72590cb3e733a15586e',
    messagingSenderId: '688190827051',
    projectId: 'phonedex-91042',
    authDomain: 'phonedex-91042.firebaseapp.com',
    storageBucket: 'phonedex-91042.firebasestorage.app',
    measurementId: 'G-88805H52K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbpDyzhgoyaYlO9oirxxdgYmDGdwF4qXo',
    appId: '1:688190827051:android:56595fd497b87fa215586e',
    messagingSenderId: '688190827051',
    projectId: 'phonedex-91042',
    storageBucket: 'phonedex-91042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWrj52_UxACb4ioO1wZfIpTo5jYyB5E_I',
    appId: '1:688190827051:ios:bb1df41bd9681ed415586e',
    messagingSenderId: '688190827051',
    projectId: 'phonedex-91042',
    storageBucket: 'phonedex-91042.firebasestorage.app',
    iosBundleId: 'com.example.pphonedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWrj52_UxACb4ioO1wZfIpTo5jYyB5E_I',
    appId: '1:688190827051:ios:bb1df41bd9681ed415586e',
    messagingSenderId: '688190827051',
    projectId: 'phonedex-91042',
    storageBucket: 'phonedex-91042.firebasestorage.app',
    iosBundleId: 'com.example.pphonedex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgRNJCnsDT5vOWHJRf-KVv1RVV-D6P9jQ',
    appId: '1:688190827051:web:51b048023c058af415586e',
    messagingSenderId: '688190827051',
    projectId: 'phonedex-91042',
    authDomain: 'phonedex-91042.firebaseapp.com',
    storageBucket: 'phonedex-91042.firebasestorage.app',
    measurementId: 'G-CZFFJLWKRR',
  );
}
